export const router = {
  ROOT: '/',
  TRANGCHU: '/trang-chu',
  BAIDANG: '/bai-dang',
  TINTUC: '/tin-tuc',
  LIENHE: '/lien-he',
  TAOBAIVIET: '/bai-dang/tao-bai-viet',
  QUANLYBAIVIET: '/bai-dang/quan-ly-bai-viet',
  SUABAIVIET: '/bai-dang/sua-bai-viet/',
  CAIDATTAIKHOAN: '/cai-dat-tai-khoan',
  BAIVIETQUANTAM: '/bai-viet-quan-tam',
  THAYDOITHONGTINCANHAN: '/thay-doi-thong-tin-ca-nhan',
  DOIMATKHAU: '/doi-mat-khau',
  DUAN: '/du-an',
};
